---
- hosts: all
  become: yes
  gather_facts: False
  roles:
    - common/ansible_ready

- hosts: [db]
  become: yes
  vars:
    network_name: survey_net
    db_root_password: gTdOChfouTy2Z3nn

  roles:
    - { role: docker/host }
    - { role: docker/network }
    - { role: application/mysql-container,
        container_name: "survey-mysql",
        db_name: "employees",
        db_user: "employees",
        db_password: "bzeUcxN1LW4BzOYy",
        config_dir: "/var/lib/docker/survey"
      }
    - { role: application/dbmanager-container,
        container_name: "survey-dbmanager",
        db_host: "survey-mysql"
      }


- hosts: [application]
  become: yes
  vars:
    network_name: survey_net
    
  roles:
    - { role: application/application-container,
        container_name: "survey-application",
        db_host: "survey-mysql",
        db_password: "bzeUcxN1LW4BzOYy",
        db_port: 3306,
        db_user: "employees"
      }

- hosts: [frontend]
  become: yes
  vars:
    network_name: survey_net
  roles:
    - { role: application/nginx-container,
        container_name: "survey-nginx",
        config_dir: "/opt/survey/nginx-conf.d",
        application_container_name: "survey-application"
      }
 
