---
- hosts: all
  vars_files:
    - vars/common.yml
  become: yes
  gather_facts: False
  roles:
    - common/ansible_ready
    - docker/host
    - docker/network

- hosts: [db]
  vars_files:
    - vars/common.yml
  become: yes
  roles:
    - { role: application/mysql-container,
        container_name: "survey-mysql"
      }
    - { role: application/dbmanager-container,
        container_name: "survey-dbmanager"
      }

- hosts: [application]
  vars_files:
    - vars/common.yml
  become: yes
  vars:
    network_name: survey_net
  roles:
    - { role: application/application-container,
        container_name: "survey-application"
      }

- hosts: [frontend]
  vars_files:
    - vars/common.yml
  become: yes
  vars:
    network_name: survey_net
  roles:
    - { role: application/nginx-container,
        container_name: "survey-nginx",
        config_dir: "/opt/survey/nginx-conf.d"
      }
 
